[default]
description = "Default permissions for the app"
permissions = [
    "allow-get-active-window",
    "allow-get-data-dir",
    "allow-set-data-dir",
    "allow-save-app-data",
    "allow-load-app-data",
]
